import type { VariableDef } from "@/lib/model/types";

const OPS = "knowledge/thesis/09-ops-capital-assumptions.md";

function usd(
  key: string,
  label: string,
  group: string,
  visibility: VariableDef["visibility"],
  defaultValue: number,
  note: string,
  cite: VariableDef["citation"]["label"] = "ASSUMPTION",
  max = 500_000,
): VariableDef {
  return {
    key,
    label,
    group,
    type: "usd",
    visibility,
    defaultValue,
    min: 0,
    max,
    citation: { label: cite, path: OPS, note },
  };
}

function pct(
  key: string,
  label: string,
  group: string,
  visibility: VariableDef["visibility"],
  defaultValue: number,
  note: string,
  cite: VariableDef["citation"]["label"] = "ASSUMPTION",
): VariableDef {
  return {
    key,
    label,
    group,
    type: "percent",
    visibility,
    defaultValue,
    min: 0,
    max: 1,
    step: 0.01,
    citation: { label: cite, path: OPS, note },
  };
}

function integer(
  key: string,
  label: string,
  group: string,
  visibility: VariableDef["visibility"],
  defaultValue: number,
  note: string,
  max = 120,
): VariableDef {
  return {
    key,
    label,
    group,
    type: "integer",
    visibility,
    defaultValue,
    min: 0,
    max,
    citation: { label: "ASSUMPTION", path: OPS, note },
  };
}

/** Department, product, Ashoka, and extra capital-partner variables. */
export const OPS_VARIABLE_DEFS: VariableDef[] = [
  integer(
    "useKpiCapitalCurve",
    "Use KPI capital curve (1) or old X% step-up (0)",
    "Capital",
    "admin",
    1,
    "KPI path to $75M Intervest + $75M other vehicles by FY10 — thesis 10",
    1,
  ),
  usd(
    "fy10HomeAumUsd",
    "Year-10 property book (funded AUM)",
    "Year-10 goals",
    "admin",
    100_000_000,
    "Ricardo goal 2026-08-23 — funded outstanding, not purchase price",
    "OPINION",
    400_000_000,
  ),
  usd(
    "fy10AutoAumUsd",
    "Year-10 auto book (funded AUM)",
    "Year-10 goals",
    "admin",
    30_000_000,
    "Ricardo goal 2026-08-23",
    "OPINION",
    200_000_000,
  ),
  usd(
    "fy10AircraftAumUsd",
    "Year-10 aircraft book (funded AUM)",
    "Year-10 goals",
    "admin",
    20_000_000,
    "Ricardo goal 2026-08-23 — last three fiscal years",
    "OPINION",
    200_000_000,
  ),
  usd(
    "fy10IntervestLineUsd",
    "Year-10 Intervest committed line",
    "Year-10 goals",
    "admin",
    75_000_000,
    "50% of the $150M book — inside the $50–100M scale band from Intervest conversations",
    "OPINION",
    200_000_000,
  ),
  usd(
    "fy10PartnerLineUsd",
    "Year-10 other partners (3 vehicles combined)",
    "Year-10 goals",
    "admin",
    75_000_000,
    "Three simulated sources after Intervest exclusivity",
    "OPINION",
    200_000_000,
  ),
  integer(
    "useDepartmentOpex",
    "Use department payroll (1) or US/Colombia lumps (0)",
    "OpCo",
    "admin",
    1,
    "1 replaces the $130k/$35k lumps with named desks",
    1,
  ),
  usd("pay.dovLoadedUsd", "Dov Tuzman MD loaded / month", "People US", "admin", 26_973, "Cash $25k + FICA/Medicare + single health — 09 §3", "ASSUMPTION", 80_000),
  usd("pay.rosarioLoadedUsd", "Rosario Davi Finance loaded / month", "People US", "admin", 16_805, "Cash $15k loaded — 09 §3", "ASSUMPTION", 80_000),
  usd("pay.ricardoLoadedUsd", "Ricardo Cidale Ops loaded / month", "People US", "admin", 26_973, "Cash $25k loaded — 09 §3", "ASSUMPTION", 80_000),
  usd("pay.tomLoadedUsd", "Tom Herman CTO loaded / month", "People US", "admin", 16_805, "Cash $15k loaded — 09 §3", "ASSUMPTION", 80_000),
  usd("dept.us.credit.loadedUsd", "US Credit loaded / FTE / month", "People US", "admin", 8_500, "Underwriter / credit analyst", "ASSUMPTION", 40_000),
  integer("dept.us.credit.fte", "US Credit FTE", "People US", "admin", 1, "Starts lean"),
  usd("dept.us.success.loadedUsd", "US Customer Success loaded / FTE / month", "People US", "admin", 7_200, "Phones, email, WhatsApp — founder channel", "ASSUMPTION", 40_000),
  integer("dept.us.success.fte", "US Customer Success base FTE", "People US", "admin", 2, "Grows with book"),
  integer("dept.csHomesPerRep", "Active homes per CS / service rep", "People US", "admin", 40, "Adds FTE as the book grows"),
  usd("dept.channelPerRepUsd", "WhatsApp + voice / rep / month", "People US", "admin", 100, "09 §5 telephony + WhatsApp reserve"),
  usd("dept.us.service.loadedUsd", "US Customer Service loaded / FTE / month", "People US", "admin", 6_400, "Collections and inbound", "ASSUMPTION", 40_000),
  integer("dept.us.service.fte", "US Customer Service base FTE", "People US", "admin", 1, "Grows with book"),
  usd("dept.us.legal.loadedUsd", "US Legal / paperwork loaded / FTE / month", "People US", "admin", 12_000, "Counsel + closings paper", "ASSUMPTION", 40_000),
  integer("dept.us.legal.fte", "US Legal FTE", "People US", "admin", 1, "AI-first still needs paper"),
  usd("dept.us.legal.contractorUsd", "US Legal contractors / month", "People US", "admin", 4_000, "Outside counsel / notaries"),
  usd("dept.us.it.loadedUsd", "US IT (ex-CTO) loaded / FTE / month", "People US", "admin", 12_000, "On top of Tom — Excel roster", "ASSUMPTION", 40_000),
  integer("dept.us.it.fte", "US IT extra FTE", "People US", "admin", 2, "VP Eng / PM style seats from the tech Excel"),
  usd("dept.us.finance.loadedUsd", "US Finance extra loaded / FTE / month", "People US", "admin", 8_000, "On top of Rosario", "ASSUMPTION", 40_000),
  integer("dept.us.finance.fte", "US Finance extra FTE", "People US", "admin", 1, "Controller / AP"),
  usd("dept.us.accounting.loadedUsd", "US Accounting loaded / FTE / month", "People US", "admin", 5_500, "Bookkeeper / close — was missing", "ASSUMPTION", 20_000),
  integer("dept.us.accounting.fte", "US Accounting FTE", "People US", "admin", 1, "Separate from Rosario and the controller"),
  usd("dept.us.sales.loadedUsd", "US Sales / origination loaded / FTE / month", "People US", "admin", 8_000, "Closer — not Customer Success", "ASSUMPTION", 30_000),
  integer("dept.us.sales.fte", "US Sales base FTE", "People US", "admin", 1, "Grows with monthly closings"),
  integer("dept.salesHomesPerRep", "New homes per sales FTE / month", "People US", "admin", 8, "Adds a closer as volume rises"),
  usd("dept.us.marketing.loadedUsd", "US Marketing loaded / FTE / month", "People US", "admin", 7_200, "Content / WhatsApp / paid social", "ASSUMPTION", 25_000),
  integer("dept.us.marketing.fte", "US Marketing FTE", "People US", "admin", 1, "AI-first still needs a human owner"),
  usd("dept.us.marketing.spendUsd", "US paid acquisition / month", "People US", "admin", 4_000, "Ads and partner referrals — not salaries", "ASSUMPTION", 80_000),
  usd("dept.officeSeatUsd", "US office seat / on-site head / month", "Workplace", "admin", 350, "Flex desk — 09 §3"),
  usd("dept.wfhStipendUsd", "US WFH stipend / remote head / month", "Workplace", "admin", 200, "09 §3"),
  pct("dept.us.wfhPct", "US staff working from home", "Workplace", "admin", 0.6, "AI-first; CS still needs coverage"),
  usd("pay.gmLoadedUsd", "Colombia GM loaded / month", "People Colombia", "admin", 18_150, "Salario integral on $15k — 09 §4", "ASSUMPTION", 40_000),
  usd("dept.co.closings.loadedUsd", "Colombia closings loaded / FTE / month", "People Colombia", "admin", 2_400, "Title / comodato desk", "ASSUMPTION", 20_000),
  integer("dept.co.closings.fte", "Colombia closings FTE", "People Colombia", "admin", 1, "Grows slowly"),
  usd("dept.co.field.loadedUsd", "Colombia field inspector loaded / FTE / month", "People Colombia", "admin", 2_200, "In-house inspections", "ASSUMPTION", 20_000),
  integer("dept.co.field.fte", "Colombia field FTE", "People Colombia", "admin", 1, "Otherwise contractors"),
  usd("dept.co.inspectContractorUsd", "Contractor inspection / close", "People Colombia", "admin", 180, "Paid when FTE capacity is short"),
  integer("dept.co.inspectFteCapacity", "Inspections an FTE can do / month", "People Colombia", "admin", 12, "Overflow goes to contractors"),
  usd("dept.co.success.loadedUsd", "Colombia CS / WhatsApp loaded / FTE / month", "People Colombia", "admin", 1_750, "Bilingual agent all-in — 09 §5", "ASSUMPTION", 10_000),
  integer("dept.co.success.fte", "Colombia CS base FTE", "People Colombia", "admin", 2, "WhatsApp-first"),
  usd("dept.co.legal.loadedUsd", "Colombia legal logistics loaded / FTE / month", "People Colombia", "admin", 3_200, "Local counsel / filings", "ASSUMPTION", 20_000),
  integer("dept.co.legal.fte", "Colombia legal FTE", "People Colombia", "admin", 1, "Paperwork"),
  usd("dept.co.officeSeatUsd", "Colombia office seat / month", "Workplace", "admin", 80, "Medellín/Cartagena desk"),
  pct("dept.co.wfhPct", "Colombia staff working from home", "Workplace", "admin", 0.3, "Field roles are on-site"),
  integer("autoStartMonth", "Auto leases start month (0 = Nov 2026)", "Autos", "user", 6, "After tranche 2 — faster fee income"),
  integer("autoMultipleX10", "Auto originations per home ×10 (30 = 3.0x)", "Autos", "admin", 30, "User asked ~3x vehicle contracts vs homes", 80),
  usd("autoTicketUsd", "Legacy auto ticket (unused — Admin → ICPs)", "Autos", "admin", 55_000, "Superseded by AUTO-1 / AUTO-2", "ASSUMPTION", 80_000),
  integer("autoTermMonths", "Legacy auto term (unused)", "Autos", "admin", 60, "Superseded by AUTO-1 / AUTO-2", 84),
  pct("autoClientRate", "Legacy auto rate (unused)", "Autos", "admin", 0.145, "Superseded by AUTO-1 / AUTO-2", "OPINION"),
  pct("autoGrowthExtraPct", "Auto growth above home curve", "Autos", "admin", 0.1, "Faster than homes"),
  integer("autoMaxPerMonth", "Auto originations cap / month", "Autos", "admin", 25, "Fills the $30M FY10 auto book", 40),
  integer("aircraftStartMonth", "Aircraft start month", "Aircraft", "user", 84, "Last 3 fiscal years", 120),
  integer("aircraftPerYear", "Aircraft originations / year after start", "Aircraft", "admin", 12, "Needed to reach the $20M FY10 aircraft book", 24),
  usd("aircraftTicketUsd", "Legacy aircraft ticket (unused — Admin → ICPs)", "Aircraft", "admin", 1_200_000, "Superseded by AIR-1 / AIR-2", "ASSUMPTION", 8_000_000),
  integer("aircraftTermMonths", "Legacy aircraft term (unused)", "Aircraft", "admin", 84, "Superseded by AIR-1 / AIR-2"),
  pct("aircraftClientRate", "Legacy aircraft rate (unused)", "Aircraft", "admin", 0.095, "Superseded by AIR-1 / AIR-2"),
  pct("insuranceCommissionPct", "Insurance / intermediation commission on new funded", "Fees Credit is paid", "user", 0.004, "40 bps seed — Credit’s take on placed cover, not a referring-partner cost"),
  pct("rentalPoolOptInPct", "Share of homes in the Ashoka rental pool", "Ashoka", "admin", 0.55, "Aug 19 pool decision"),
  pct("ashokaMgmtFeePct", "Ashoka STR management fee of gross rent", "Ashoka", "admin", 0.2, "20% base — 09 §7", "ASSUMPTION"),
  usd("ashokaGrossRentUsd", "Gross STR rent / pooled home / month", "Ashoka", "admin", 1_800, "Before Ashoka fee and Tamarindo share"),
  usd("ashokaRepairUsd", "Repair / maintenance spend / pooled home / month", "Ashoka", "admin", 120, "Charge-through base"),
  pct("ashokaRepairMarkupPct", "Ashoka markup on repairs", "Ashoka", "admin", 0.15, "Related-party must be market"),
  integer("partner2StartMonth", "Capital partner 2 start month", "Capital partners", "admin", 36, "Intervest exclusive first 3 years", 120),
  usd("partner2Usd", "Partner 2 year-10 line (legacy curve)", "Capital partners", "admin", 25_000_000, "Used only when KPI curve is off", "OPINION", 200_000_000),
  pct("partner2Yield", "Partner 2 vehicle yield", "Capital partners", "admin", 0.1, "8.5–11.5% band — 09 §2", "ASSUMPTION"),
  integer("partner3StartMonth", "Capital partner 3 start month", "Capital partners", "admin", 60, "Years 6–7", 120),
  usd("partner3Usd", "Partner 3 committed line", "Capital partners", "admin", 25_000_000, "Third vehicle", "OPINION", 400_000_000),
  pct("partner3Yield", "Partner 3 vehicle yield", "Capital partners", "admin", 0.095, "8.0–11.0% band — 09 §2", "ASSUMPTION"),
  integer("partner4StartMonth", "Capital partner 4 start month", "Capital partners", "admin", 84, "Years 8–10 / aircraft era", 120),
  usd("partner4Usd", "Partner 4 year-10 line (legacy curve)", "Capital partners", "admin", 25_000_000, "Used only when KPI curve is off", "OPINION", 200_000_000),
  pct("partner4Yield", "Partner 4 vehicle yield", "Capital partners", "admin", 0.09, "7.5–10.5% band — 09 §2", "ASSUMPTION"),
];
