import type { VariableDef } from "@/lib/model/types";

const PATH = "knowledge/thesis/11-equity.md";

export const EQUITY_VARIABLE_DEFS: VariableDef[] = [
  {
    key: "founderCount",
    label: "Tamarindo partners (equal shares, names TBD)",
    group: "Equity",
    type: "integer",
    visibility: "admin",
    defaultValue: 5,
    min: 2,
    max: 8,
    citation: {
      label: "ASSUMPTION",
      path: PATH,
      note: "Five equal partners until ownership is assigned",
    },
  },
  {
    key: "founderPayHalfMonths",
    label: "Months of reduced founder pay",
    group: "Equity",
    type: "integer",
    visibility: "admin",
    defaultValue: 8,
    min: 0,
    max: 24,
    citation: {
      label: "OPINION",
      path: PATH,
      note: "First 8 months of operations",
    },
  },
  {
    key: "founderPayHalfPct",
    label: "Founder pay during the reduced window",
    group: "Equity",
    type: "percent",
    visibility: "admin",
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.05,
    citation: {
      label: "OPINION",
      path: PATH,
      note: "50% of loaded named US pay",
    },
  },
  {
    key: "equityRound1Month",
    label: "Round 1 month (0 = Nov 2026)",
    group: "Equity",
    type: "integer",
    visibility: "admin",
    defaultValue: 0,
    min: 0,
    max: 120,
    citation: { label: "OPINION", path: PATH, note: "$2M to start operations" },
  },
  {
    key: "equityRound1Usd",
    label: "Round 1 raise",
    group: "Equity",
    type: "usd",
    visibility: "admin",
    defaultValue: 2_000_000,
    min: 0,
    max: 20_000_000,
    citation: {
      label: "OPINION",
      path: PATH,
      note: "Smallest check first to get started; FY1 burn is ~$1.65M",
    },
  },
  {
    key: "equityRound1PreMoneyUsd",
    label: "Round 1 pre-money",
    group: "Equity",
    type: "usd",
    visibility: "admin",
    defaultValue: 10_000_000,
    min: 0,
    max: 100_000_000,
    citation: { label: "OPINION", path: PATH, note: "Initial $10M pre-money" },
  },
  {
    key: "equityRound2Month",
    label: "Round 2 month",
    group: "Equity",
    type: "integer",
    visibility: "admin",
    defaultValue: 12,
    min: 0,
    max: 120,
    citation: {
      label: "ASSUMPTION",
      path: PATH,
      note: "After the first fiscal year — confirm timing",
    },
  },
  {
    key: "equityRound2Usd",
    label: "Round 2 raise",
    group: "Equity",
    type: "usd",
    visibility: "admin",
    defaultValue: 2_250_000,
    min: 0,
    max: 20_000_000,
    citation: { label: "OPINION", path: PATH, note: "Second check — $2.25M" },
  },
  {
    key: "equityRound2PreMoneyUsd",
    label: "Round 2 pre-money",
    group: "Equity",
    type: "usd",
    visibility: "admin",
    defaultValue: 15_000_000,
    min: 0,
    max: 200_000_000,
    citation: { label: "OPINION", path: PATH, note: "$15M after the $10M round" },
  },
  {
    key: "equityRound3Month",
    label: "Round 3 month",
    group: "Equity",
    type: "integer",
    visibility: "admin",
    defaultValue: 24,
    min: 0,
    max: 120,
    citation: {
      label: "ASSUMPTION",
      path: PATH,
      note: "After the second fiscal year — confirm timing",
    },
  },
  {
    key: "equityRound3Usd",
    label: "Round 3 raise",
    group: "Equity",
    type: "usd",
    visibility: "admin",
    defaultValue: 2_250_000,
    min: 0,
    max: 20_000_000,
    citation: { label: "OPINION", path: PATH, note: "Third check — $2.25M" },
  },
  {
    key: "equityRound3PreMoneyUsd",
    label: "Round 3 pre-money",
    group: "Equity",
    type: "usd",
    visibility: "admin",
    defaultValue: 20_000_000,
    min: 0,
    max: 400_000_000,
    citation: { label: "OPINION", path: PATH, note: "$20M after the $15M round" },
  },
  {
    key: "equityRound4Month",
    label: "Round 4 month (optional)",
    group: "Equity",
    type: "integer",
    visibility: "admin",
    defaultValue: 36,
    min: 0,
    max: 120,
    citation: { label: "ASSUMPTION", path: PATH, note: "Slot for a fourth tranche" },
  },
  {
    key: "equityRound4Usd",
    label: "Round 4 raise (0 = off)",
    group: "Equity",
    type: "usd",
    visibility: "admin",
    defaultValue: 0,
    min: 0,
    max: 20_000_000,
    citation: { label: "ASSUMPTION", path: PATH, note: "Fourth tranche left empty" },
  },
  {
    key: "equityRound4PreMoneyUsd",
    label: "Round 4 pre-money",
    group: "Equity",
    type: "usd",
    visibility: "admin",
    defaultValue: 25_000_000,
    min: 0,
    max: 400_000_000,
    citation: { label: "ASSUMPTION", path: PATH, note: "Only if round 4 is turned on" },
  },
];
